In [7]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

[10 20 30 40 50]
Mean: 30.0
Maximum: 50
Minimum: 10

In [8]:
import pandas as pd

data = {
    "Name": ["Rahul", "Aman", "Priya"],
    "Age": [20, 21, 20],
    "Marks": [85, 92, 78]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     92
2  Priya   20     78

In [9]:
print("Average marks:", df["Marks"].mean())
print("Highest marks:", df["Marks"].max())

Average marks: 85.0
Highest marks: 92

In [10]:
df

    Name  Age  Marks
0  Rahul   20     85
1   Aman   21     92
2  Priya   20     78

In [11]:
import pandas as pd

df = pd.read_csv("../data/Maths.csv", encoding="cp1252")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/Maths.csv'

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.shape
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [ ]:
df.shape

(891, 12)

In [ ]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [ ]:
df.info

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [ ]:
df.tail

<bound method NDFrame.tail of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
df.head()

NameError: name 'df' is not defined

In [ ]:
df

NameError: name 'df' is not defined

In [ ]:
import pandas as pd
df = pd.read_csv("../data/Titanic-Dataset.csv")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
import pandas as pd

df = pd.read_csv("../data/Titanic-Dataset.csv")

df.head()

SystemError: <class 'pandas._libs.tslib.__pyx_defaults'> returned a result with an exception set

In [ ]:
import pandas as pd

df = pd.read_csv("../data/Titanic-Dataset.csv")

SystemError: <class 'pandas._libs.tslib.__pyx_defaults'> returned a result with an exception set

In [ ]:
import pandas as pd
df = pd.read_csv("../data/Titanic-Dataset.csv")

SystemError: <class 'pandas._libs.tslib.__pyx_defaults'> returned a result with an exception set

In [ ]:
import pandas as pd
df = pd.read_csv("../data/Titanic-Dataset.csv")

ImportError: DLL load failed while importing json: An Application Control policy has blocked this file.

In [ ]:
import sys
print(sys.executable)

c:\Users\RAHUL\Documents\AI&ML_PROJ\AMAZON_ML\.venv\Scripts\python.exe

In [ ]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.5.3
3.0.6

In [ ]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
X = df[["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]]

y = df["Survived"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
X_train.head()

     Pclass     Sex   Age  SibSp  Parch     Fare Embarked
331       1    male  45.5      0      0  28.5000        S
733       2    male  23.0      0      0  13.0000        S
382       3    male  32.0      0      0   7.9250        S
704       3    male  26.0      1      0   7.8542        S
813       3  female   6.0      4      2  31.2750        S

In [ ]:
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42
)

In [ ]:
train_df.to_csv("../data/train.csv", index=False)
test_df.to_csv("../data/test.csv", index=False)

In [ ]:
print(train_df.shape)
print(test_df.shape)

(712, 12)
(179, 12)

In [ ]:
numeric_features = ["Pclass", "Age", "SibSp", "Parch", "Fare"]

categorical_features = ["Sex", "Embarked"]

print(numeric_features)
print(categorical_features)

['Pclass', 'Age', 'SibSp', 'Parch', 'Fare']
['Sex', 'Embarked']

In [ ]:
from sklearn.impute import SimpleImputer

ImportError: DLL load failed while importing _sgd_fast: An Application Control policy has blocked this file.

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
numeric_imputer = SimpleImputer(strategy="median")

In [ ]:
SimpleImputer(strategy="most_frequent")

SimpleImputer(strategy='most_frequent')

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [65]:
model = LogisticRegression(max_iter=1000)
model_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])
model_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Pclass', 'Age', 'SibSp',
                                                   'Parch', 'Fare']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked'])])),
                ('model', LogisticRegression(max_iter=1000))])

In [ ]:
y_pred = model_pipeline.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8100558659217877

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[90 15]
 [19 55]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [ ]:
print(classification_report(y_test, y_pred))

NameError: name 'classification_report' is not defined

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

NameError: name 'model_pipeline' is not defined

In [ ]:
scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

NameError: name 'cross_val_score' is not defined

In [ ]:
scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("CV scores:", scores)
print("Mean CV accuracy:", scores.mean())

NameError: name 'cross_val_score' is not defined

In [12]:
from sklearn.model_selection import cross_val_score

print("cross_val_score imported successfully")

cross_val_score imported successfully

In [13]:
print(cross_val_score)

<function cross_val_score at 0x0000029D36ACE820>

In [14]:
scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("CV scores:", scores)
print("Mean CV accuracy:", scores.mean())

NameError: name 'model_pipeline' is not defined

In [15]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [16]:
df = pd.read_csv("../data/Titanic-Dataset.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
X = df[[
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked"
]]

y = df["Survived"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (891, 7)
y shape: (891,)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (712, 7)
Testing data: (179, 7)

In [19]:
numeric_features = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare"
]

categorical_features = [
    "Sex",
    "Embarked"
]

In [20]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [21]:
model = LogisticRegression(max_iter=1000)

model_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", model)
])

In [22]:
model_pipeline.fit(X_train, y_train)

print("Model training completed!")

Model training completed!

In [23]:
y_pred = model_pipeline.predict(X_test)

print("Predictions completed!")
print(y_pred[:20])

Predictions completed!
[0 0 0 1 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0]

In [24]:
accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.8100558659217877

In [25]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[90 15]
 [19 55]]

In [26]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [27]:
scores = cross_val_score(
    model_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("CV Scores:", scores)
print("Mean CV Accuracy:", scores.mean())

CV Scores: [0.77094972 0.78651685 0.78089888 0.76966292 0.82022472]
Mean CV Accuracy: 0.7856506182913816

In [28]:
from sklearn.tree import DecisionTreeClassifier

decision_tree = DecisionTreeClassifier(
    random_state=42
)

dt_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", decision_tree)
])

In [29]:
dt_pipeline.fit(X_train, y_train)

dt_pred = dt_pipeline.predict(X_test)

dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.776536312849162

In [30]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

Confusion Matrix:
[[83 22]
 [18 56]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.79      0.81       105
           1       0.72      0.76      0.74        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

In [31]:
dt_scores = cross_val_score(
    dt_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Decision Tree CV Scores:", dt_scores)
print("Decision Tree Mean CV Accuracy:", dt_scores.mean())

Decision Tree CV Scores: [0.75418994 0.79213483 0.80898876 0.73595506 0.81460674]
Decision Tree Mean CV Accuracy: 0.781175067478501

In [32]:
from sklearn.ensemble import RandomForestClassifier

random_forest = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", random_forest)
])

In [33]:
rf_pipeline.fit(X_train, y_train)

rf_pred = rf_pipeline.predict(X_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.8044692737430168

In [34]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, rf_pred))

print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

Confusion Matrix:
[[89 16]
 [19 55]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.85      0.84       105
           1       0.77      0.74      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179

In [35]:
rf_scores = cross_val_score(
    rf_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Random Forest CV Scores:", rf_scores)
print("Random Forest Mean CV Accuracy:", rf_scores.mean())

Random Forest CV Scores: [0.77094972 0.80898876 0.84831461 0.76966292 0.83146067]
Random Forest Mean CV Accuracy: 0.805875337392505

In [36]:
print("MODEL COMPARISON")
print("-----------------------------")
print("Logistic Regression:", scores.mean())
print("Decision Tree:      ", dt_scores.mean())
print("Random Forest:      ", rf_scores.mean())

MODEL COMPARISON
-----------------------------
Logistic Regression: 0.7856506182913816
Decision Tree:       0.781175067478501
Random Forest:       0.805875337392505

In [37]:
dt_train_pred = dt_pipeline.predict(X_train)

dt_train_accuracy = accuracy_score(
    y_train,
    dt_train_pred
)

print("Decision Tree Training Accuracy:", dt_train_accuracy)
print("Decision Tree Test Accuracy:", dt_accuracy)

Decision Tree Training Accuracy: 0.9789325842696629
Decision Tree Test Accuracy: 0.776536312849162

In [38]:
decision_tree_2 = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt_pipeline_2 = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", decision_tree_2)
])

dt_pipeline_2.fit(X_train, y_train)

dt2_pred = dt_pipeline_2.predict(X_test)

print(
    "Decision Tree with max_depth=5:",
    accuracy_score(y_test, dt2_pred)
)

Decision Tree with max_depth=5: 0.7988826815642458

In [39]:
from xgboost import XGBClassifier

In [40]:
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

In [41]:
xgb_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", xgb_model)
])

In [42]:
xgb_pipeline.fit(X_train, y_train)

xgb_pred = xgb_pipeline.predict(X_test)

xgb_accuracy = accuracy_score(y_test, xgb_pred)

print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.8268156424581006

In [43]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))

print("\nClassification Report:")
print(classification_report(y_test, xgb_pred))

Confusion Matrix:
[[92 13]
 [18 56]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86       105
           1       0.81      0.76      0.78        74

    accuracy                           0.83       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

In [44]:
xgb_scores = cross_val_score(
    xgb_pipeline,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("XGBoost CV Scores:", xgb_scores)
print("XGBoost Mean CV Accuracy:", xgb_scores.mean())

XGBoost CV Scores: [0.81005587 0.82022472 0.86516854 0.82022472 0.85393258]
XGBoost Mean CV Accuracy: 0.8339212855439081

In [45]:
print("FINAL MODEL COMPARISON")
print("==============================")

print("Logistic Regression:", scores.mean())
print("Decision Tree:      ", dt_scores.mean())
print("Random Forest:      ", rf_scores.mean())
print("XGBoost:             ", xgb_scores.mean())

FINAL MODEL COMPARISON
==============================
Logistic Regression: 0.7856506182913816
Decision Tree:       0.781175067478501
Random Forest:       0.805875337392505
XGBoost:              0.8339212855439081

In [46]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

df[["SibSp", "Parch", "FamilySize"]].head(10)

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1
5      0      0           1
6      0      0           1
7      3      1           5
8      0      2           3
9      1      0           2

In [47]:
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)

df[["FamilySize", "IsAlone"]].head(10)

   FamilySize  IsAlone
0           2        0
1           2        0
2           1        1
3           2        0
4           1        1
5           1        1
6           1        1
7           5        0
8           3        0
9           2        0

In [48]:
df["Title"] = df["Name"].str.extract(r",\s*([^.]*)\.")

df[["Name", "Title"]].head(10)

                                                Name   Title
0                            Braund, Mr. Owen Harris      Mr
1  Cumings, Mrs. John Bradley (Florence Briggs Th...     Mrs
2                             Heikkinen, Miss. Laina    Miss
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)     Mrs
4                           Allen, Mr. William Henry      Mr
5                                   Moran, Mr. James      Mr
6                            McCarthy, Mr. Timothy J      Mr
7                     Palsson, Master. Gosta Leonard  Master
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)     Mrs
9                Nasser, Mrs. Nicholas (Adele Achem)     Mrs

In [49]:
df["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Major             2
Mlle              2
Col               2
Don               1
Mme               1
Ms                1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [50]:
common_titles = [
    "Mr",
    "Miss",
    "Mrs",
    "Master"
]

df["Title"] = df["Title"].where(
    df["Title"].isin(common_titles),
    "Rare"
)

df["Title"].value_counts()

Title
Mr        517
Miss      182
Mrs       125
Master     40
Rare       27
Name: count, dtype: int64

In [51]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=[
        "Child",
        "Teenager",
        "YoungAdult",
        "Adult",
        "Senior"
    ]
)

df[["Age", "AgeGroup"]].head(15)

     Age    AgeGroup
0   22.0  YoungAdult
1   38.0       Adult
2   26.0  YoungAdult
3   35.0  YoungAdult
4   35.0  YoungAdult
5    NaN         NaN
6   54.0       Adult
7    2.0       Child
8   27.0  YoungAdult
9   14.0    Teenager
10   4.0       Child
11  58.0       Adult
12  20.0  YoungAdult
13  39.0       Adult
14  14.0    Teenager

In [52]:
print(df.groupby("FamilySize")["Survived"].mean())
print(df.groupby("IsAlone")["Survived"].mean())
print(df.groupby("Title")["Survived"].mean())
print(df.groupby("AgeGroup", observed=True)["Survived"].mean())

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64
IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64
Title
Master    0.575000
Miss      0.697802
Mr        0.156673
Mrs       0.792000
Rare      0.444444
Name: Survived, dtype: float64
AgeGroup
Child         0.579710
Teenager      0.428571
YoungAdult    0.382682
Adult         0.400000
Senior        0.227273
Name: Survived, dtype: float64

In [53]:
X_fe = df[[
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked",
    "FamilySize",
    "IsAlone",
    "Title",
    "AgeGroup"
]]

y_fe = df["Survived"]

In [54]:
numeric_features_fe = [
    "Pclass",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "FamilySize",
    "IsAlone"
]

categorical_features_fe = [
    "Sex",
    "Embarked",
    "Title",
    "AgeGroup"
]

In [55]:
numeric_transformer_fe = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer_fe = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor_fe = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer_fe, numeric_features_fe),
        ("cat", categorical_transformer_fe, categorical_features_fe)
    ]
)

In [56]:
X_fe_train, X_fe_test, y_fe_train, y_fe_test = train_test_split(
    X_fe,
    y_fe,
    test_size=0.2,
    random_state=42
)

In [57]:
xgb_fe_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

xgb_fe_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor_fe),
    ("model", xgb_fe_model)
])

In [58]:
xgb_fe_pipeline.fit(
    X_fe_train,
    y_fe_train
)

xgb_fe_pred = xgb_fe_pipeline.predict(X_fe_test)

xgb_fe_accuracy = accuracy_score(
    y_fe_test,
    xgb_fe_pred
)

print("XGBoost with Feature Engineering Accuracy:",
      xgb_fe_accuracy)

XGBoost with Feature Engineering Accuracy: 0.8324022346368715

In [59]:
xgb_fe_scores = cross_val_score(
    xgb_fe_pipeline,
    X_fe,
    y_fe,
    cv=5,
    scoring="accuracy"
)

print("CV Scores:", xgb_fe_scores)
print("Mean CV Accuracy:", xgb_fe_scores.mean())

CV Scores: [0.83240223 0.8258427  0.85393258 0.80337079 0.84831461]
Mean CV Accuracy: 0.832772581758835

In [60]:
print("Original XGBoost CV:",
      xgb_scores.mean())

print("Feature Engineered XGBoost CV:",
      xgb_fe_scores.mean())

Original XGBoost CV: 0.8339212855439081
Feature Engineered XGBoost CV: 0.832772581758835

In [61]:
from sklearn.model_selection import GridSearchCV

In [62]:
xgb_for_tuning = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_tuning_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor_fe),
    ("model", xgb_for_tuning)
])

In [63]:
param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [3, 4, 5],
    "model__learning_rate": [0.05, 0.1]
}

In [64]:
grid_search = GridSearchCV(
    estimator=xgb_tuning_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_search.fit(X_fe, y_fe)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='median'))]),
                                                                         ['Pclass',
                                                                          'Age',
                                                                          'SibSp',
                                                                          'Parch',
                                                                          'Fare',
                                                                          'FamilySize',
                                                                          'IsAlone']),
                                                                        ('cat',
                                                                         Pipeline(steps=[('imputer',
                                                                                          SimpleImputer(strategy='most_frequent')),
                                                                                         ('encoder',
                                                                                          OneHotEncoder(handle_unknown='ignore')...
                                                      max_cat_to_onehot=None,
                                                      max_delta_step=None,
                                                      max_depth=None,
                                                      max_leaves=None,
                                                      min_child_weight=None,
                                                      missing=nan,
                                                      monotone_constraints=None,
                                                      multi_strategy=None,
                                                      n_estimators=None,
                                                      n_jobs=None,
                                                      num_parallel_tree=None, ...))]),
             n_jobs=-1,
             param_grid={'model__learning_rate': [0.05, 0.1],
                         'model__max_depth': [3, 4, 5],
                         'model__n_estimators': [100, 200]},
             scoring='accuracy')

In [66]:
print("Best Parameters:")
print(grid_search.best_params_)

Best Parameters:
{'model__learning_rate': 0.1, 'model__max_depth': 5, 'model__n_estimators': 100}

In [67]:
print("Best CV Accuracy:")
print(grid_search.best_score_)

Best CV Accuracy:
0.8383842822170612

In [68]:
best_model = grid_search.best_estimator_

print(best_model)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  ['Pclass', 'Age', 'SibSp',
                                                   'Parch', 'Fare',
                                                   'FamilySize', 'IsAlone']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Sex', 'Embarked', 'Title...
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=5, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=100, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [69]:
best_pred = best_model.predict(X_fe_test)

best_accuracy = accuracy_score(
    y_fe_test,
    best_pred
)

print("Tuned XGBoost Test Accuracy:", best_accuracy)

Tuned XGBoost Test Accuracy: 0.9217877094972067

In [70]:
print(classification_report(
    y_fe_test,
    best_pred
))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93       105
           1       0.89      0.92      0.91        74

    accuracy                           0.92       179
   macro avg       0.92      0.92      0.92       179
weighted avg       0.92      0.92      0.92       179

In [71]:
print(confusion_matrix(
    y_fe_test,
    best_pred
))

[[97  8]
 [ 6 68]]

In [72]:
print("Original XGBoost CV:",
      xgb_scores.mean())

print("Feature Engineered XGBoost CV:",
      xgb_fe_scores.mean())

print("Tuned XGBoost CV:",
      grid_search.best_score_)

print("Tuned XGBoost Test:",
      best_accuracy)

Original XGBoost CV: 0.8339212855439081
Feature Engineered XGBoost CV: 0.832772581758835
Tuned XGBoost CV: 0.8383842822170612
Tuned XGBoost Test: 0.9217877094972067

In [73]:
from sklearn.model_selection import RandomizedSearchCV

In [74]:
param_distributions = {
    "model__n_estimators": [100, 200, 300, 400],
    "model__max_depth": [3, 4, 5, 6, 7],
    "model__learning_rate": [0.01, 0.03, 0.05, 0.1],
    "model__subsample": [0.7, 0.8, 0.9, 1.0],
    "model__colsample_bytree": [0.7, 0.8, 0.9, 1.0]
}

In [75]:
random_search = RandomizedSearchCV(
    estimator=xgb_tuning_pipeline,
    param_distributions=param_distributions,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=42,
    n_jobs=-1
)

random_search.fit(X_fe, y_fe)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='median'))]),
                                                                               ['Pclass',
                                                                                'Age',
                                                                                'SibSp',
                                                                                'Parch',
                                                                                'Fare',
                                                                                'FamilySize',
                                                                                'IsAlone']),
                                                                              ('cat',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(strategy='most_frequent')),
                                                                                               ('encoder',
                                                                                                OneHotEncoder(handle_unknown='ig...
                                                            multi_strategy=None,
                                                            n_estimators=None,
                                                            n_jobs=None,
                                                            num_parallel_tree=None, ...))]),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'model__colsample_bytree': [0.7, 0.8,
                                                                    0.9, 1.0],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__max_depth': [3, 4, 5, 6, 7],
                                        'model__n_estimators': [100, 200, 300,
                                                                400],
                                        'model__subsample': [0.7, 0.8, 0.9,
                                                             1.0]},
                   random_state=42, scoring='accuracy')

In [76]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV Accuracy:")
print(random_search.best_score_)

Best Parameters:
{'model__subsample': 0.9, 'model__n_estimators': 100, 'model__max_depth': 6, 'model__learning_rate': 0.03, 'model__colsample_bytree': 0.9}

Best CV Accuracy:
0.8417425145941875

In [77]:
best_random_model = random_search.best_estimator_

In [78]:
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Precision: 0.7857142857142857
Recall: 0.7432432432432432
F1 Score: 0.7638888888888888

In [79]:
print(y.value_counts())

print("\nClass proportions:")
print(y.value_counts(normalize=True))

Survived
0    549
1    342
Name: count, dtype: int64

Class proportions:
Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [80]:
from lightgbm import LGBMClassifier

In [81]:
lgbm_model = LGBMClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    verbosity=-1
)

In [82]:
lgbm_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor_fe),
    ("model", lgbm_model)
])

In [83]:
lgbm_pipeline.fit(
    X_fe_train,
    y_fe_train
)

lgbm_pred = lgbm_pipeline.predict(
    X_fe_test
)

lgbm_accuracy = accuracy_score(
    y_fe_test,
    lgbm_pred
)

print("LightGBM Accuracy:", lgbm_accuracy)

LightGBM Accuracy: 0.8324022346368715

In [84]:
lgbm_scores = cross_val_score(
    lgbm_pipeline,
    X_fe,
    y_fe,
    cv=5,
    scoring="accuracy"
)

print("LightGBM CV Scores:", lgbm_scores)
print("LightGBM Mean CV Accuracy:", lgbm_scores.mean())

LightGBM CV Scores: [0.80446927 0.80898876 0.87078652 0.8258427  0.8258427 ]
LightGBM Mean CV Accuracy: 0.827185989580064

In [85]:
print(classification_report(
    y_fe_test,
    lgbm_pred
))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86       105
           1       0.80      0.80      0.80        74

    accuracy                           0.83       179
   macro avg       0.83      0.83      0.83       179
weighted avg       0.83      0.83      0.83       179

In [86]:
from catboost import CatBoostClassifier

In [87]:
cat_model = CatBoostClassifier(
    iterations=200,
    learning_rate=0.05,
    depth=5,
    random_seed=42,
    verbose=0
)

In [88]:
cat_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor_fe),
    ("model", cat_model)
])

In [89]:
cat_pipeline.fit(
    X_fe_train,
    y_fe_train
)

cat_pred = cat_pipeline.predict(
    X_fe_test
)

cat_accuracy = accuracy_score(
    y_fe_test,
    cat_pred
)

print("CatBoost Accuracy:", cat_accuracy)

CatBoost Accuracy: 0.8212290502793296

In [90]:
cat_scores = cross_val_score(
    cat_pipeline,
    X_fe,
    y_fe,
    cv=5,
    scoring="accuracy"
)

print("CatBoost CV Scores:", cat_scores)
print("CatBoost Mean CV Accuracy:", cat_scores.mean())

CatBoost CV Scores: [0.82681564 0.80898876 0.84269663 0.79775281 0.85955056]
CatBoost Mean CV Accuracy: 0.8271608813006089

In [91]:
print("BOOSTING MODEL COMPARISON")
print("==============================")

print("XGBoost:  ", xgb_fe_scores.mean())
print("LightGBM: ", lgbm_scores.mean())
print("CatBoost: ", cat_scores.mean())

BOOSTING MODEL COMPARISON
==============================
XGBoost:   0.832772581758835
LightGBM:  0.827185989580064
CatBoost:  0.8271608813006089

In [92]:
# Load the actual test data
test_df = pd.read_csv("../data/test.csv")

# Keep the same features used by your final model
X_final_test = test_df[[
    "Pclass",
    "Sex",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked",
    "FamilySize",
    "IsAlone",
    "Title",
    "AgeGroup"
]]

# Generate predictions
final_predictions = best_model.predict(X_final_test)

print(final_predictions[:20])

KeyError: "['FamilySize', 'IsAlone', 'Title', 'AgeGroup'] not in index"

In [93]:
final_predictions = best_model.predict(X_fe_test)

print("Number of predictions:", len(final_predictions))
print("First 20 predictions:")
print(final_predictions[:20])

Number of predictions: 179
First 20 predictions:
[1 0 0 1 1 1 1 0 1 1 1 0 0 0 0 1 1 1 0 0]

In [94]:
submission = pd.DataFrame({
    "PassengerId": df.loc[X_fe_test.index, "PassengerId"].values,
    "Survived": final_predictions
})

submission.head(10)

   PassengerId  Survived
0          710         1
1          440         0
2          841         0
3          721         1
4           40         1
5          291         1
6          301         1
7          334         0
8          209         1
9          137         1

In [95]:
print("Shape:", submission.shape)

print("\nColumns:")
print(submission.columns)

print("\nMissing values:")
print(submission.isnull().sum())

print("\nPrediction counts:")
print(submission["Survived"].value_counts())

Shape: (179, 2)

Columns:
Index(['PassengerId', 'Survived'], dtype='str')

Missing values:
PassengerId    0
Survived       0
dtype: int64

Prediction counts:
Survived
0    103
1     76
Name: count, dtype: int64

In [96]:
submission.to_csv(
    "../submissions/final_submission.csv",
    index=False
)

print("Final submission saved!")

Final submission saved!

In [97]:
final_submission = pd.read_csv(
    "../submissions/final_submission.csv"
)

print(final_submission.head())
print()
print("Shape:", final_submission.shape)
print("Columns:", list(final_submission.columns))

   PassengerId  Survived
0          710         1
1          440         0
2          841         0
3          721         1
4           40         1

Shape: (179, 2)
Columns: ['PassengerId', 'Survived']